version: "3"

networks:
  overlay:
    driver: bridge

services:
    sql-server-db:
        image: "mcr.microsoft.com/mssql/server"
        networks:
            - overlay
        environment:
            SA_PASSWORD: "mm.p@ss1234!#"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"
